{% set name = "msgpack-cpp" %}
{% set version = "4.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/msgpack/msgpack-c/releases/download/cpp-4.1.2/msgpack-cxx-{{ version }}.tar.gz
  sha256: eeddd7faeacbc12e10052bd1e3ec78bd26c69bfbbea9f9264c7ffce9b1ede7b1
build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - make  # [unix]
  host:
    - boost-cpp
  run:
    - boost-cpp

test:
  commands:
    - test -f $PREFIX/include/msgpack.hpp                       # [unix]
    - if not exist %LIBRARY_INC%\\msgpack.hpp exit 1            # [win]
    
about:
  home: https://github.com/msgpack/msgpack-c
  license: BSL-1.0
  license_file: LICENSE.txt
  summary: MessagePack implementation for C++.
  doc_url: https://github.com/msgpack/msgpack-c/wiki
  dev_url: https://github.com/msgpack/msgpack-c

extra:
  recipe-maintainers:
    - lunarlanding
